//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaliAftotrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Sredstvas = new HashSet<Sredstva>();
        }
    
        public int IdUser { get; set; }
        public string F { get; set; }
        public string I { get; set; }
        public string O { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FIO
        {
            get
            {
                return $"{F} {I} {O}";
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sredstva> Sredstvas { get; set; }
    }
}
