//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaliAftotrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voditeli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voditeli()
        {
            this.Sredstvas = new HashSet<Sredstva>();
        }
    
        public int IdVoditeli { get; set; }
        public string F { get; set; }
        public string I { get; set; }
        public string O { get; set; }
        public string AutoPrava { get; set; }
        public bool Active { get; set; }

        public string ActiveText
        {
            get
            {
                return (Active) ? "Активен" : "Неактивен";
            }
        }
        public string FIO
        {
            get
            {
                return $"{F} {I} {O}";
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sredstva> Sredstvas { get; set; }
    }
}
